// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/[locale]" | "/[locale]/[...rest]" | "/[locale]/bazaar" | "/[locale]/browse" | "/[locale]/categories" | "/[locale]/categories/[slug]" | "/[locale]/conversations" | "/[locale]/conversations/[id]" | "/[locale]/delete-account" | "/[locale]/forgot-password" | "/[locale]/listings/[id]" | "/[locale]/listings/[id]/edit" | "/[locale]/listings/new" | "/[locale]/login" | "/[locale]/my-listings" | "/[locale]/my-listings/[id]" | "/[locale]/privacy" | "/[locale]/profile" | "/[locale]/profile/edit" | "/[locale]/reset-password" | "/[locale]/saved" | "/[locale]/sellers/[id]" | "/[locale]/settings/blocked-users" | "/[locale]/signup" | "/[locale]/users/[id]"
type AppRouteHandlerRoutes = "/api/auth/cable" | "/api/auth/delete" | "/api/auth/forgot-password" | "/api/auth/google" | "/api/auth/login" | "/api/auth/logout" | "/api/auth/register" | "/api/auth/reset-password" | "/api/auth/session" | "/api/health" | "/api/me/[...path]" | "/api/proxy/[...path]"
type PageRoutes = never
type LayoutRoutes = "/" | "/[locale]"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/[locale]": { "locale": string; }
  "/[locale]/[...rest]": { "locale": string; "rest": string[]; }
  "/[locale]/bazaar": { "locale": string; }
  "/[locale]/browse": { "locale": string; }
  "/[locale]/categories": { "locale": string; }
  "/[locale]/categories/[slug]": { "locale": string; "slug": string; }
  "/[locale]/conversations": { "locale": string; }
  "/[locale]/conversations/[id]": { "locale": string; "id": string; }
  "/[locale]/delete-account": { "locale": string; }
  "/[locale]/forgot-password": { "locale": string; }
  "/[locale]/listings/[id]": { "locale": string; "id": string; }
  "/[locale]/listings/[id]/edit": { "locale": string; "id": string; }
  "/[locale]/listings/new": { "locale": string; }
  "/[locale]/login": { "locale": string; }
  "/[locale]/my-listings": { "locale": string; }
  "/[locale]/my-listings/[id]": { "locale": string; "id": string; }
  "/[locale]/privacy": { "locale": string; }
  "/[locale]/profile": { "locale": string; }
  "/[locale]/profile/edit": { "locale": string; }
  "/[locale]/reset-password": { "locale": string; }
  "/[locale]/saved": { "locale": string; }
  "/[locale]/sellers/[id]": { "locale": string; "id": string; }
  "/[locale]/settings/blocked-users": { "locale": string; }
  "/[locale]/signup": { "locale": string; }
  "/[locale]/users/[id]": { "locale": string; "id": string; }
  "/api/auth/cable": {}
  "/api/auth/delete": {}
  "/api/auth/forgot-password": {}
  "/api/auth/google": {}
  "/api/auth/login": {}
  "/api/auth/logout": {}
  "/api/auth/register": {}
  "/api/auth/reset-password": {}
  "/api/auth/session": {}
  "/api/health": {}
  "/api/me/[...path]": { "path": string[]; }
  "/api/proxy/[...path]": { "path": string[]; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/[locale]": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
